import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import localFont from "next/font/local"
const myFont = localFont ({src : "./Fonts/Bahij_TheSansArabic-ExtraBold.ttf"})

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={myFont.className}>
<div className="bg-second">
        <Header/>
        {children}
        <Footer/>
</div>
        </body>
    </html>
  );
}
